name: 'Test'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  skipci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[Skip CI] ${{ contains(github.event.head_commit.message, '[skip ci]') }}"

  test:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]
        os:  [windows-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install packages (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y -qq
        #sudo apt-get install -y -qq sudo make gcc xvfb libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev ubuntu-restricted-extras libgstreamer-plugins-base1.0-dev
        sudo apt-get install -y -qq sudo make gcc xvfb libgtk-3-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        pip install pytest
        xvfb-run --auto-servernum pytest -W ignore::DeprecationWarning
    - name: Test with pytest (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        pip install pytest
        pytest -W ignore::DeprecationWarning
    - name: build with pyinstaller
      if: startsWith(matrix.os, 'windows')
      run: |
        pip install pyinstaller
        pyinstaller --name PyFuzzy-renamer --windowed --icon pyfuzzyrenamer.ico pyfuzzyrenamer\__main__.py
